language: node_js
node_js:
  - 8

sudo: false

script:
  - yarn lint
  - yarn test

after_script:
  - yarn coveralls
  - yarn codeclimate

branches:
   only:
   - master

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"

notifications:
  email:
    recipients:
    - luis@urrutia.me
    on_success: change
    on_failure: always
